server:
  port: 8082
spring:
  application:
    name: shopping
  datasource:
      url: jdbc:mysql://localhost/blogs?characterEncoding=utf-8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource